import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"
import SearchBar from "@/component/SearchBar/SearchBar";
import SideBar from "@/component/SideBar/SideBar";
import styles from './for-you/page.module.css';
import { StoreProvider } from "@/lib/provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function nonHomePageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
                <div className={styles['wrapper']}>
                  <StoreProvider>
                      <SearchBar />
                      <SideBar/>
                      {children}
                    </StoreProvider>
                </div>
      </body>
    </html>
  );
}